In [2]:
import tensorflow as tf
import pandas as pd
import numpy as np
data = pd.read_excel(r'C:\Users\basil\OneDrive\Documents\lab_3_data.xlsx')
testData = pd.read_excel(r'C:\Users\basil\OneDrive\Documents\lab_3_test_data.xlsx')
print(data)
d = data.pop('d')
dTest = testData.pop('d')

         x1      x2      x3       d
0    0.8799  0.7998  0.3972  0.8399
1    0.5700  0.5111  0.2418  0.6258
2    0.6796  0.4117  0.3370  0.6622
3    0.3567  0.2967  0.6037  0.5969
4    0.3866  0.8390  0.0232  0.5316
..      ...     ...     ...     ...
195  0.0339  0.4669  0.1526  0.3250
196  0.0080  0.8988  0.4201  0.5404
197  0.9955  0.8897  0.6175  0.9360
198  0.7408  0.5351  0.2732  0.6949
199  0.6843  0.3737  0.1562  0.5625

[200 rows x 4 columns]


In [5]:

tf_dataset = tf.data.Dataset.from_tensor_slices((data.values, d.values))
tf_test_dataset = tf.data.Dataset.from_tensor_slices((testData.values, dTest.values))
x,y = [],[]
xtes,ytes = [],[]
for feature,value in tf_dataset.as_numpy_iterator() :
    x.append(feature)
    y.append(value)
    
for feature,value in tf_test_dataset.as_numpy_iterator() :
    xtes.append(feature)
    ytes.append(value)
x

[array([0.8799, 0.7998, 0.3972]),
 array([0.57  , 0.5111, 0.2418]),
 array([0.6796, 0.4117, 0.337 ]),
 array([0.3567, 0.2967, 0.6037]),
 array([0.3866, 0.839 , 0.0232]),
 array([0.0271, 0.7788, 0.7445]),
 array([0.8174, 0.8422, 0.3229]),
 array([0.6027, 0.1468, 0.3759]),
 array([0.1203, 0.326 , 0.5419]),
 array([0.1325, 0.2082, 0.4934]),
 array([0.695 , 1.    , 0.4321]),
 array([0.0036, 0.194 , 0.3274]),
 array([0.265 , 0.0161, 0.5947]),
 array([0.5849, 0.6019, 0.4376]),
 array([0.0108, 0.3538, 0.181 ]),
 array([0.9008, 0.7264, 0.9184]),
 array([0.0023, 0.9659, 0.3182]),
 array([0.1366, 0.6357, 0.6967]),
 array([0.8621, 0.7353, 0.2742]),
 array([0.0682, 0.9624, 0.4211]),
 array([0.6112, 0.6014, 0.5254]),
 array([0.003 , 0.7585, 0.8928]),
 array([0.7644, 0.5964, 0.0407]),
 array([0.6441, 0.2097, 0.5847]),
 array([0.0803, 0.3799, 0.602 ]),
 array([0.1908, 0.8046, 0.5402]),
 array([0.6937, 0.3967, 0.6055]),
 array([0.2591, 0.0582, 0.3978]),
 array([0.4241, 0.185 , 0.9066]),
 array([0.3332

In [6]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(10, input_shape=(3,), activation='relu'))
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

In [7]:
model.compile(loss='mean_squared_error', metrics=[tf.keras.metrics.MeanSquaredError()])

xt = np.asarray(x)
yt = np.asarray(y)
model.fit(xt,yt, epochs=60, batch_size=10)

_, accuracy = model.evaluate(xt,yt)
print('Accuracy: %.2f' % (accuracy*100))

y_pred = model.predict

Epoch 1/60
20/20 [==============================] - 0s 778us/step - loss: 0.0425 - mean_squared_error: 0.0425
Epoch 2/60
20/20 [==============================] - 0s 610us/step - loss: 0.0324 - mean_squared_error: 0.0324
Epoch 3/60
20/20 [==============================] - 0s 574us/step - loss: 0.0283 - mean_squared_error: 0.0283
Epoch 4/60
20/20 [==============================] - 0s 627us/step - loss: 0.0258 - mean_squared_error: 0.0258
Epoch 5/60
20/20 [==============================] - 0s 653us/step - loss: 0.0241 - mean_squared_error: 0.0241
Epoch 6/60
20/20 [==============================] - 0s 600us/step - loss: 0.0227 - mean_squared_error: 0.0227
Epoch 7/60
20/20 [==============================] - 0s 627us/step - loss: 0.0215 - mean_squared_error: 0.0215
Epoch 8/60
20/20 [==============================] - 0s 627us/step - loss: 0.0204 - mean_squared_error: 0.0204
Epoch 9/60
20/20 [==============================] - 0s 627us/step - loss: 0.0193 - mean_squared_error: 0.0193
Epoch 10/6

In [8]:
xtest = np.asarray(xtes)
ytest = np.asarray(ytes)

_, accuracy = model.evaluate(xtest,ytest)
print('Accuracy: %.2f' % (accuracy*100))

y_pred = model.predict(xtest)
y_pred

1/1 [==============================] - 0s 15ms/step - loss: 3.7888e-04 - mean_squared_error: 3.7888e-04
Accuracy: 0.04
1/1 [==============================] - 0s 47ms/step


array([[0.49971867],
       [0.6259589 ],
       [0.5034145 ],
       [0.69882214],
       [0.29500812],
       [0.7682657 ],
       [0.55057544],
       [0.7004066 ],
       [0.5224584 ],
       [0.59944844],
       [0.69032055],
       [0.6771612 ],
       [0.32814687],
       [0.79887307],
       [0.47015327],
       [0.827585  ],
       [0.7502083 ],
       [0.56047595],
       [0.8080348 ],
       [0.49771157]], dtype=float32)